format_version: 3
pipelines:
  akka-http-bootcamp-deploy:
    group: defaultGroup
    label_template: ${akka-http-bootcamp-build}
    lock_behavior: none
    display_order: -1
    materials:
      akka-http-bootcamp-build:
        ignore_for_scheduling: false
        pipeline: akka-http-bootcamp
        stage: docker_push
      goCDProject:
        git: https://github.com/rnsandeep/goCDProject
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - deploy:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          deploy:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - bin/deploy2.sh
                command: /bin/bash
                working_directory: httpakka
                run_if: passed
