format_version: 3
pipelines:
  akka-http-bootcamp:
    group: defaultGroup
    label_template: akka-http-bootcamp-${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git:
        git: https://github.com/rnsandeep/goCDProject
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - sbt_test_build:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          sbt_test_build:
            timeout: 0
            environment_variables:
              GO_LABEL: ${GO_PIPELINE_LABEL}
            artifacts:
            - build:
                source: httpakka/assembly.jar
                destination: ''
            tasks:
            - exec:
                arguments:
                - test
                - assembly
                command: sbt
                working_directory: httpakka
                run_if: passed
            - exec:
                arguments:
                - bin/move_jar.sh
                command: /bin/bash
                working_directory: httpakka
                run_if: passed
    - docker_build:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        environment_variables:
          /usr/bin/env: /bin/bash
        jobs:
          docker-build:
            timeout: 0
            tasks:
            - fetch:
                is_file: true
                source: assembly.jar
                destination: httpakka
                pipeline: akka-http-bootcamp
                stage: sbt_test_build
                job: sbt_test_build
                artifact_origin: gocd
                run_if: passed
            - exec:
                arguments:
                - bin/deploy.sh
                command: /bin/bash
                working_directory: httpakka
                run_if: passed
    - docker_push:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          dockerpush:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - bin/push.sh
                command: /bin/bash
                working_directory: httpakka
                run_if: passed
